import type { Metadata } from "next";
import "./globals.css";
import { raleway } from "./fonts";

export const metadata: Metadata = {
  title: "Robiul Islam  | Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${raleway.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
